In [2]:
import sys
import os
import warnings

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(os.path.realpath("__file__")), ".."))
)

warnings.simplefilter(action="ignore", category=FutureWarning)

In [2]:
import pandas as pd

from handyman import (
    get_company_info,
    get_officers,
    get_prices,
    get_analyst_price_targets,
    get_analyst_recommendations,
    get_analyst_upgrades_downgrades,
    get_options,
    get_institutional_holders,
    get_major_holders,
    get_insider_transactions,
    get_fundamentals,
    get_eps_revisions,
    get_earnings_surprises,
    get_eps_estimates,
    get_revenue_estimates,
    get_growth_estimates,
)

tickers = ["AAPL", "MSFT", "GE", "NVDA", "JPM", "META", "FOX"]

In [3]:
get_company_info(
    tickers="AAPL",
    # get_latest=True
)

,DATE,TICKER,ADDRESS1,CITY,STATE,ZIP,COUNTRY,PHONE,WEBSITE,INDUSTRY,...,REGULARMARKETDAYRANGE,REGULARMARKETCHANGEPERCENT,REGULARMARKETPRICE,DISPLAYNAME,TRAILINGPEGRATIO,IPOEXPECTEDDATE,ADDRESS2,FAX,INDUSTRYSYMBOL,PEGRATIO
0,2025-11-22,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,265.82 - 273.315,1.968070,271.49,Apple,2.7474,nan,nan,nan,nan,NaN
1,2025-11-24,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,270.9 - 276.98,1.631740,275.92,Apple,2.7474,nan,nan,nan,nan,NaN
2,2025-12-02,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,282.6301 - 287.4,1.091486,286.19,Apple,2.8649,nan,nan,nan,nan,NaN
3,2025-12-08,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,276.15 - 279.6693,-0.319242,277.89,Apple,2.4662,nan,nan,nan,nan,NaN
4,2025-12-15,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,272.84 - 280.05,-1.498500,274.11,Apple,2.8161,nan,nan,nan,nan,NaN
5,2025-12-22,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,270.505 - 273.88,-0.986594,270.97,Apple,2.7695,nan,nan,nan,nan,NaN
6,2025-12-30,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,272.28 - 274.08,-0.197256,273.22,Apple,2.7704,None,None,None,None,NaN
7,2026-01-05,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,266.14 - 271.5,-1.383710,267.26,Apple,2.7425,None,None,None,None,NaN
8,2026-01-12,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,256.8 - 261.3,0.339286,260.25,Apple,2.6248,None,None,None,None,NaN
9,2026-01-20,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,243.42 - 254.79,-3.450650,246.70,Apple,2.5859,None,None,None,None,NaN
10,2026-01-26,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,249.8 - 256.56,2.971300,255.41,Apple,2.5847,None,None,None,None,NaN
11,2026-02-02,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,259.205 - 270.49,4.058116,270.01,Apple,2.6259,None,None,None,None,NaN
12,2026-02-09,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,271.7 - 278.2,-1.166050,274.62,Apple,2.5258,None,None,None,None,NaN
13,2026-02-17,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,255.54 - 266.29,3.166790,263.88,Apple,2.3828,None,None,None,None,NaN
14,2026-02-23,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,263.381 - 269.43,0.604734,266.18,Apple,2.4662,None,None,None,None,NaN
15,2026-03-02,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,260.2 - 266.53,0.204409,264.72,Apple,2.3855,None,None,None,None,NaN
16,2026-03-03,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,260.13 - 265.56,-0.366425,263.75,Apple,2.3708,None,None,None,None,NaN
17,2026-03-04,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,261.42 - 266.15,-0.466355,262.52,Apple,2.3621,None,None,None,None,NaN
18,2026-03-04,AAPL,One Apple Park Way,Cupertino,CA,95014,United States,(408) 996-1010,https://www.apple.com,Consumer Electronics,...,261.42 - 266.15,-0.466355,262.52,Apple,2.3621,None,None,None,None,NaN

In [9]:
from handyman import get_index_holdings, get_llm_holdings

get_index_holdings(start_date="2026-03-05").sort_values("INDEX")

,DATE,INDEX,TICKER,NAME,MARKET_VALUE,WEIGHT,QUANTITY,PRICE,LOCATION,EXCHANGE,CURRENCY,FX_RATE
752,2026-03-05,Russell 1000,HLT,HILTON WORLDWIDE HOLDINGS INC,5.047785e+07,0.001103,165550.0,304.91,United States,NYSE,USD,1.0
795,2026-03-05,Russell 1000,IRM,IRON MOUNTAIN INC,2.310698e+07,0.000505,214271.0,107.84,United States,NYSE,USD,1.0
794,2026-03-05,Russell 1000,IRDM,IRIDIUM COMMUNICATIONS INC,1.681460e+06,0.000037,68603.0,24.51,United States,NASDAQ,USD,1.0
793,2026-03-05,Russell 1000,IR,INGERSOLL RAND INC,2.687688e+07,0.000587,292649.0,91.84,United States,NYSE,USD,1.0
792,2026-03-05,Russell 1000,IQV,IQVIA HOLDINGS INC,2.176575e+07,0.000476,122362.0,177.88,United States,NYSE,USD,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
212,2026-03-05,S&P 500,RTX,RTX CORP,3.549093e+09,0.004771,16995946.0,208.82,United States,NYSE,USD,1.0
213,2026-03-05,S&P 500,RVTY,REVVITY INC,1.414210e+08,0.000190,1435892.0,98.49,United States,NYSE,USD,1.0
214,2026-03-05,S&P 500,SBAC,SBA COMMUNICATIONS REIT CORP CLASS,2.653327e+08,0.000357,1350775.0,196.43,United States,NASDAQ,USD,1.0
207,2026-03-05,S&P 500,ROK,ROCKWELL AUTOMATION INC,5.455584e+08,0.000733,1423134.0,383.35,United States,NYSE,USD,1.0
1505,2026-03-05,S&P 500,FFIV,F5 INC,2.092101e+08,0.000281,731197.0,286.12,United States,NASDAQ,USD,1.0

In [4]:
from connectors.azure_data_source import default_azure_data_source
from sql.script_factory import SQLClient

engine = default_azure_data_source.get_engine()
sql_client = SQLClient()

query = sql_client.build_select_all_query(table_name="address")
address_df = default_azure_data_source.read_sql_table(engine=engine, query=query)

address_df

,ADDRESS1,CITY,COUNTRY,LAT,LON
0,2788 San Tomas Expressway,Santa Clara,United States,37.370544,-121.967081
1,One Apple Park Way,Cupertino,United States,37.335651,-122.014050
2,One Microsoft Way,Redmond,United States,47.641070,-122.126882
3,410 Terry Avenue North,Seattle,United States,47.622298,-122.336500
4,3421 Hillview Ave,Palo Alto,United States,37.399027,-122.144416
...,...,...,...,...,...
1064,00 Crescent Ct.,Dallas,United States,32.793905,-96.804062
1065,10500 Liberty Parkway,Birmingham,United States,33.477218,-86.703816
1066,4114 Center at North Hills Street,Raleigh,United States,35.837166,-78.644073
1067,601 Merritt Seven,Norwalk,United States,41.117597,-73.407897
1068,900 Sylvan Avenue,Englewood Cliffs,United States,40.898686,-73.939288