In [1]:
import sys
import os
import warnings

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(os.path.realpath("__file__")), ".."))
)

warnings.simplefilter(action="ignore", category=FutureWarning)

In [75]:
import pandas as pd

from handyman import (
    get_company_info,
    get_officers,
    get_prices,
    get_analyst_price_targets,
    get_analyst_recommendations,
    get_analyst_upgrades_downgrades,
    get_options,
    get_institutional_holders,
    get_major_holders,
    get_insider_transactions,
    get_fundamentals,
    get_eps_revisions,
    get_earnings_surprises,
    get_eps_estimates,
    get_revenue_estimates,
    get_growth_estimates,
)

tickers = ["AAPL", "MSFT", "GE", "NVDA", "JPM", "META", "FOX"]

In [108]:
get_major_holders(
    tickers="AAPL",
    # get_latest=True
)

        DATE TICKER                         INDEX       VALUE
0 2026-02-27   AAPL           insidersPercentHeld     0.01840
1 2026-02-27   AAPL       institutionsPercentHeld     0.65176
2 2026-02-27   AAPL  institutionsFloatPercentHeld     0.66397
3 2026-02-27   AAPL             institutionsCount  7491.00000
4 2026-03-03   AAPL  institutionsFloatPercentHeld     0.66403
5 2026-03-03   AAPL       institutionsPercentHeld     0.65181
6 2026-03-03   AAPL             institutionsCount  7494.00000

In [99]:
from handyman import get_index_holdings, get_llm_holdings

get_index_holdings(tickers="AAPL")

,DATE,INDEX,TICKER,NAME,MARKET_VALUE,WEIGHT,QUANTITY,PRICE,LOCATION,EXCHANGE,CURRENCY,FX_RATE
0,2025-11-24,S&P 500,AAPL,APPLE INC,5.029702e+10,0.071587,185262875.0,271.49,United States,NASDAQ,USD,1.0
1,2025-11-24,Russell 1000,AAPL,APPLE INC,2.882402e+09,0.065359,10616972.0,271.49,United States,NASDAQ,USD,1.0
2,2025-11-25,S&P 500,AAPL,APPLE INC,5.120897e+10,0.071645,185593551.0,275.92,United States,NASDAQ,USD,1.0
3,2025-11-25,Russell 1000,AAPL,APPLE INC,2.904334e+09,0.065423,10526000.0,275.92,United States,NASDAQ,USD,1.0
4,2025-11-26,S&P 500,AAPL,APPLE INC,5.143759e+10,0.071274,185715379.0,276.97,United States,NASDAQ,USD,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
129,2026-02-27,Russell 1000,AAPL,APPLE INC,2.913353e+09,0.062799,10673578.0,272.95,United States,NASDAQ,USD,1.0
130,2026-03-02,S&P 500,AAPL,APPLE INC,4.976209e+10,0.066439,188364334.0,264.18,United States,NASDAQ,USD,1.0
131,2026-03-02,Russell 1000,AAPL,APPLE INC,2.786519e+09,0.061052,10547805.0,264.18,United States,NASDAQ,USD,1.0
132,2026-03-03,S&P 500,AAPL,APPLE INC,4.986610e+10,0.066548,188372984.0,264.72,United States,NASDAQ,USD,1.0
133,2026-03-03,Russell 1000,AAPL,APPLE INC,2.796807e+09,0.061117,10565153.0,264.72,United States,NASDAQ,USD,1.0